name: ci-trigger-other-workflow
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        repos: ['juanonsoftware/PocGitAsPublicSubmodule']
    timeout-minutes: 5
    
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: workflow_02
          repo: ${{ matrix.repo }}
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          
