name: workflow_01
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        repo: ['juanonsoftware/PocGitAsPublicSubmodule']
    timeout-minutes: 5
    
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: workflow_02
          repo: ${{ matrix.repo }}
          inputs: '{ "message": "blah blah", "something": false }'
          
